name: telegram message
on: [push]
jobs:

  build:
    name: Notification
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            üî• ${{ github.actor }} created commit:
            üìù Commit message: ${{ github.event.commits[0].message }}
            
            üí© See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
          disable_web_page_preview: true
      - name: send telegram sticker
        run: |
          curl -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendSticker \
            -d chat_id=${{ secrets.TELEGRAM_TO }} \
            -d sticker=CAACAgIAAxkBAAEEWEJiR1m_4rk1FQEt_fTLlZecKD5RUgACbxIAAlP0sEnt1eGAMPBOWCME \
